### ISSUE TITLE
arki-query with expa fails with message "too many open files"

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#213]
With arkimet v1.21-1:

```
[arkimet@arkiope8 ~]$ arki-query --data --qmacro="expa 2020-02-13" --file=00.expa /arkivio/arkimet/dataset/cosmo_5M_ita > out.grib
Traceback (most recent call last):
  File "/usr/bin/arki-query", line 11, in <module>
  File "/usr/bin/arki-query", line 7, in main
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/base.py", line 74, in main
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/query.py", line 138, in run
  File "/etc/arkimet/qmacro/expa.py", line 98, in query_data
  File "/etc/arkimet/qmacro/expa.py", line 84, in row_to_md
RuntimeError: cannot open file /arkivio/arkimet/dataset/cosmo_5M_ita/lock: Too many open files
```

We began to experience this error with the new arkimet release. The error is raised with expa query only.

**Comment by brancomat** [comment]
the error seems inconsistent with the actual open files situation, unless it peaks somehow opening instantly other ~800 files
```
[arkimet~]$ ulimit -n
1024
# lsof -u arkimet | awk '{print $9}' | sort | uniq | wc -l
221
# cat /proc/sys/fs/file-nr
2304	0	794517
```

**Comment by edigiacomo** [comment]
The error is not raised using a different dataset
```
[arkimet@arkiope8 ~]$ arki-query --data --qmacro="expa 2020-02-13" --file=00.expa /arkivio/arkimet/dataset/cosmo_2I > /tmp/out.grib
[arkimet@arkiope8 ~]$ ls -la /tmp/out.grib
-rw-rw-r-- 1 arkimet arkimet 807672 Feb 13 17:07 /tmp/out.grib
[arkimet@arkiope8 ~]$ grib_count /tmp/out.grib
1
```

**Comment by edigiacomo** [comment]
Sorry, I used a smaller expa in the previous example.

It seems that the problem is in the dimension of the expa
```
[arkimet@arkiope8 ~]$ wc -l 00.expa
1033 00.expa
[arkimet@arkiope8 ~]$ arki-query --data --qmacro="expa 2020-02-13" --file=00.expa /arkivio/arkimet/dataset/cosmo_5M_ita > /tmp/out.grib
Traceback (most recent call last):
  File "/usr/bin/arki-query", line 11, in <module>
  File "/usr/bin/arki-query", line 7, in main
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/base.py", line 74, in main
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/query.py", line 138, in run
  File "/etc/arkimet/qmacro/expa.py", line 98, in query_data
  File "/etc/arkimet/qmacro/expa.py", line 84, in row_to_md
RuntimeError: cannot open file /arkivio/arkimet/dataset/cosmo_5M_ita/lock: Too many open files
[arkimet@arkiope8 ~]$ grib_count /tmp/out.grib
0
```

But using a smaller expa, everything works fine:

```
[arkimet@arkiope8 ~]$ wc -l 00.expa
499 00.expa
[arkimet@arkiope8 ~]$ arki-query --data --qmacro="expa 2020-02-13" --file=00.expa /arkivio/arkimet/dataset/cosmo_5M_ita > /tmp/out.grib
[arkimet@arkiope8 ~]$ grib_count /tmp/out.grib
499
```

**Comment by spanezz** [comment]
Riprodotto in test suite. Querando dati, i metadati estratti dal database tengono un link al file di dati da cui dovranno leggere. Al momento non c'è un riuso dei segmenti tra una `query_data` e l'altra, per cui, facendo una query_data che legge mille dati da un segmento, tutti i dati usano lo stesso file descriptor. Facendo invece mille query_data che leggono un dato ognuno, ci si ritrova con mille dati che usano mille file descriptor diversi.

**Comment by brancomat** [comment]
nota: declasso a devel blocking per un workaround by @edigiacomo sulle expa più pasciute
