### ISSUE TITLE
500 Internal Server Error getting bufr

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/arkimet#214]
```
 wget "127.0.0.1:8090/dataset/opendata-er/query?style=postprocess&command=bufr-filter report%3Dsimnbo&query=reftime%3A%3Barea%3AGRIB%3A or GRIB%3Atype%3Dmob%3Bproduct%3ABUFR%3At%3Dsimnbo"
--2020-02-24 19:29:13--  http://127.0.0.1:8090/dataset/opendata-er/query?style=postprocess&command=bufr-filter%20report%3Dsimnbo&query=reftime%3A%3Barea%3AGRIB%3A%20or%20GRIB%3Atype%3Dmob%3Bproduct%3ABUFR%3At%3Dsimnbo
Connessione a 127.0.0.1:8090...connesso.
Richiesta HTTP inviata, in attesa di risposta... 500 Internal Server Error
2020-02-24 19:29:13 ERRORE 500: Internal Server Error.
```
in the error log:

```
2020-02-24 19:32:01,593 ERROR Exception caught after headers have been sent
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/arkimet/server/views.py", line 281, in run
    self.stream()
  File "/usr/lib/python3.6/site-packages/arkimet/server/views.py", line 307, in stream
    summary.write(self.handler.wfile, format=self.request.values.get("style", "binary").strip())
SystemError: <built-in method write of arkimet.Summary object at 0x7fad6c022ac8> returned NULL without setting an error
```

**Comment by spanezz** [comment]
Manually closing after a misspelled "Fixes"
