### ISSUE TITLE
arki_dataset_concurrent_* tests fail with TEST_VERBOSE=1

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#220]
From https://travis-ci.org/github/ARPA-SIMC/arkimet/jobs/661978370

```
make check TEST_VERBOSE=1
...
arki_dataset_ondisk2_index.concurrent: value ' ' is different than the expected 'H'

  dataset/ondisk2/index-test.cc:288:actual(readHang.waitUntilHung()) == 'H'

arki_dataset_concurrent_grib_ondisk2.read_read: value '_' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_grib_ondisk2.read_write: value '_' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_grib_simple_plain.read_read: value '_' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_grib_simple_plain.read_write: value '_' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_grib_simple_sqlite.read_read: value 'o' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_grib_simple_sqlite.read_write: value 'o' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_grib_iseg.read_read: value 'o' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_grib_iseg.read_write: value 'o' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_bufr_ondisk2.read_read: value 'o' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_bufr_ondisk2.read_write: value 'o' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_bufr_simple_plain.read_read: value 'd' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_bufr_simple_plain.read_write: value 'd' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_bufr_simple_sqlite.read_read: value 'd' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_bufr_simple_sqlite.read_write: value 'd' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_bufr_iseg.read_read: value 'd' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_bufr_iseg.read_write: value 'd' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_vm2_ondisk2.read_read: value '.' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_vm2_ondisk2.read_write: value '.' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_vm2_simple_plain.read_read: value '.' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_vm2_simple_plain.read_write: value '.' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_vm2_simple_sqlite.read_read: value '.' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_vm2_simple_sqlite.read_write: value '.' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_vm2_iseg.read_read: value '.' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_vm2_iseg.read_write: value 't' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_odim_ondisk2.read_read: value 't' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_odim_ondisk2.read_write: value 't' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_odim_simple_plain.read_read: value 't' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_odim_simple_plain.read_write: value 't' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_odim_simple_sqlite.read_read: value 't' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_odim_simple_sqlite.read_write: value 't' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_odim_iseg.read_read: value 'a' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected

arki_dataset_concurrent_odim_iseg.read_write: value 'a' is different than the expected 'H'

  dataset-concurrency-test.cc:76:actual(wait_until_ready()) == expected
```

Instead, `make check` without `TEST_VERBOSE=1` is executed successfully (https://travis-ci.org/github/ARPA-SIMC/arkimet/jobs/662010828).

**Comment by edigiacomo** [comment]
I added the "enhancement" label because we don't need the TEST_VERBOSE=1 in our builds.

**Comment by spanezz** [comment]
I cannot reproduce it. I tried a dozen times with:
```
make check TEST_VERBOSE=1 TEST_ONLY="*concur*" -C arki
```
(and also without `TEST_ONLY`) and I got all tests succeded every time.

If you can reproduce it reliably, can you tell me on which system, so I can try it there?

**Comment by edigiacomo** [comment]
https://travis-ci.org/github/ARPA-SIMC/arkimet/builds/692463836 still fails but I can't reproduce the issue on our systems.

**Comment by edigiacomo** [comment]
On `otto.metarpa` (CentOS8):

```
$ make check TEST_VERBOSE=1
...
======================================================================
FAIL: test_progress (tests.test_dataset.TestDatasetReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/autofs/nfshomes/edigiacomo/src/arkimet/python/tests/test_dataset.py", line 305, in test_progress
    self.assertGreaterEqual(progress.update_called, 2)
AssertionError: 1 not greater than or equal to 2

======================================================================
FAIL: test_progress_merged (tests.test_dataset.TestDatasetReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/autofs/nfshomes/edigiacomo/src/arkimet/python/tests/test_dataset.py", line 407, in test_progress_merged
    self.assertGreaterEqual(progress.update_called, 2)
AssertionError: 1 not greater than or equal to 2

----------------------------------------------------------------------
Ran 227 tests in 19.762s

FAILED (SKIP=12, failures=2)
```

**Comment by edigiacomo** [comment]
Closing the issue, tests are now successful.
