### ISSUE TITLE
arki-query --qmacro=expa exit with status 0 even when the query is not fullfilled

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#221]
```
$ rpm -qi arkimet | grep -i version
Version     : 1.23
$ arki-query --data --qmacro='expa 2020-03-16' --file=12.expa http://arkiope.metarpa:8090 > out.grib
WARNING expa 2020-03-16 failed: POST http://arkiope.metarpa:8090/query got response code 500: row 1:'ds:cosmo_2I. d:@. t:1200. s:GRIB1/0/0/0. l:g02. v:t.' did not produce any results
$ echo $?
0
```

**Comment by spanezz** [comment]
I managed to pinpoint the issue to https://github.com/ARPA-SIMC/arkimet/blob/master/python/arki-query.cc#L215:
```py
                try {
                    self->processor->process(*reader, reader->name());
                } catch (PythonException&) {
                    throw;
                } catch (std::exception& e) {
                    arki::nag::warning("%s failed: %s", reader->name().c_str(), e.what());
                    all_successful = false;
                }
```
which is like this since years.

I don't know/remember why we are converting errors to warnings in that point. Should I try to leave errors as errors, and we see if and what breaks instead?

**Comment by edigiacomo** [comment]
Thank you Enrico! The problem for me is not the warning instead of the error, but the exit status: our programs relies on the exit status of the expa querymacro to execute the periodic run.

With an older version, the exit status is 2

```
$ rpm -qi arkimet | grep -i version
Version     : 1.14

$ arki-query --data --qmacro='expa 2020-03-23' 'ds:cosmo_2I. d:@. t:1200. s:GRIB1/0/0/0. l:g02. v:t.' http://arkiope.metarpa:8090 > out.grib
expa 2020-03-23 failed: POST http://arkiope.metarpa:8090/query got response code 500: row 1:'ds:cosmo_2I. d:@. t:1200. s:GRIB1/0/0/0. l:g02. v:t.' did not produce any results

$ echo $?
2
```

**Comment by edigiacomo** [comment]
I think that the difference is how the return value of the query function is handled.

See https://github.com/ARPA-SIMC/arkimet/blob/v1.14-1/arki/runtime/arki-query.cc#L65-L68 and https://github.com/ARPA-SIMC/arkimet/blob/v1.14-1/arki/runtime/source.cc#L246-L253

I think that a possibile fix to replicate the v1.14 behaviour could be to check the return value of arki_query.query_qmacro in `python/arkimet/cmdline/query.py`:

```
diff --git a/python/arkimet/cmdline/query.py b/python/arkimet/cmdline/query.py
index 17251715..b32e551b 100644
--- a/python/arkimet/cmdline/query.py
+++ b/python/arkimet/cmdline/query.py
@@ -171,11 +171,16 @@ class Query(AppConfigMixin, AppWithProcessor):
                     progress=progress,
             )

+            all_successful = True
+
             if self.args.stdin:
-                arki_query.query_file(sys.stdin, self.args.stdin)
+                all_successful = arki_query.query_file(sys.stdin, self.args.stdin)
             elif self.args.merged:
-                arki_query.query_merged()
+                all_successful = arki_query.query_merged()
             elif self.args.qmacro:
-                arki_query.query_qmacro(self.args.qmacro, qmacro_query)
+                all_successful = arki_query.query_qmacro(self.args.qmacro, qmacro_query)
             else:
-                arki_query.query_sections()
+                all_successful = arki_query.query_sections()
+
+            if not all_successful:
+                raise Exit(2)
```

**Comment by spanezz** [comment]
Ok, the original exit code [were](https://github.com/ARPA-SIMC/arkimet/blob/v1.1-1/src/arki-query.cc):
```c++
		if (all_successful)
			return 0;
		else
			return 2;
```

Meaning: 0 if all was ok, 1 if there was an unhandled error, 2 if there was an error in one of the sources queried, but other sources were ok.

If this distinction still useful, I can try to recreate it?

**Comment by edigiacomo** [comment]
Yes, thank you! The distinction can be useful.

**Comment by spanezz** [comment]
I see now that the qmacro error sets `all_successful` to `false`, and the problem was that the error returned was not passed to `sys.exit`. I'm meanwhile implementing that.

**Comment by spanezz** [comment]
For the actual error results, we went with posix, I'll stick with that

**Comment by edigiacomo** [comment]
It seems that the bug came back in version v.1.41 and only with `--data` option.

The client exits with status 0:

```
$ arki-query --verbose --debug --data --qmacro="expa 2023-06-01" --file=12.expa http://arkiope.metarpa:8090 > /dev/null ; echo $?
INFO Running query macro expa 2023-06-01 remotely on http://arkiope.metarpa:8090
INFO Processing expa 2023-06-01...
0
```

But the server logs the error

```
$ tail -n11  /var/log/arkimet/server-error.log
2022-06-01 11:42:06,806 ERROR Exception caught before headers have been sent
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/arkimet/server/views.py", line 149, in response
    yield
  File "/usr/lib/python3.6/site-packages/arkimet/server/views.py", line 498, in post
    summary = self.get_dataset_reader().query_summary(self.get_query())
  File "/etc/arkimet/qmacro/expa.py", line 107, in query_data
    res.append(self.row_to_md(row, with_data))
  File "/etc/arkimet/qmacro/expa.py", line 95, in row_to_md
    raise RuntimeError("row {}:{} did not produce any results".format(row.lineno, repr(row.line)))
RuntimeError: row 1:'ds:cosmo_5M_ita_any. d:@. t:1200. s:C006. l:G00. v:TP.' did not produce any results
```

The summary behaves correctly

```
$ arki-query --verbose --debug --summary --qmacro="expa 2023-06-01" --file=12.expa http://arkiope.metarpa:8090 > /dev/null ; echo $?
INFO Running query macro expa 2023-06-01 remotely on http://arkiope.metarpa:8090
INFO Processing expa 2023-06-01...
WARNING expa 2023-06-01 failed: POST http://arkiope.metarpa:8090/summary got response code 500: row 1:'ds:cosmo_5M_ita_any. d:@. t:1200. s:C006. l:G00. v:TP.' did not produce any results

70
```

The expa file is here: [12.expa.zip](https://github.com/ARPA-SIMC/arkimet/files/8813012/12.expa.zip)

**Comment by spanezz** [comment]
The error logged seems to be part of a query summary, rather than a data expa. I'll try and see if I can access the server log

**Comment by spanezz** [comment]
Here's an updated server log extract:
```
2022-06-10 15:58:53,521 ERROR Exception caught after headers have been sent
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/arkimet/server/views.py", line 317, in response
    yield
  File "/usr/lib/python3.6/site-packages/arkimet/server/views.py", line 366, in post
    data_start_hook=self.send_headers)
  File "/etc/arkimet/qmacro/expa.py", line 107, in query_data
    res.append(self.row_to_md(row, with_data))
  File "/etc/arkimet/qmacro/expa.py", line 95, in row_to_md
    raise RuntimeError("row {}:{} did not produce any results".format(row.lineno, repr(row.line)))
RuntimeError: row 1:'ds:cosmo_5M_ita_any. d:@. t:1200. s:C006. l:G00. v:TP.' did not produce any results
```

**Comment by spanezz** [comment]
And the problem is here:
```
2022-06-10 15:58:53,521 ERROR Exception caught after headers have been sent
```
Something already triggered sending headers, so arki-server has no way to report a problem it encoutered afterwards. This is related to #71.

Howver, no data was sent, so it looks like the sending of headers is incorrectly triggered. I'll keep looking

**Comment by spanezz** [comment]
The change that triggered the regression is 874aa58c411bc5c8952513b72bc6e857ea337fdc.

Now the function that sends the headers is called after arguments have been validated, and not when the first byte is sent.

Since expa queries need to give an error if the query cannot be satisfied, I need to either reinstate the hack of sending headers when the first byte is sent, or to introduce a validation step that checks if the expa query is satisfiable.

Alternatively, the better fix would be to implement #71.

How urgent is this?

**Comment by edigiacomo** [comment]
The bug still persists but we have managed to avoid it in the last 18 months. Therefore I remove the "production blocking" tag.
