### ISSUE TITLE
Error in scanning DPC odim volumes

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/arkimet#227]
After an upgrade (presumably 1.14->1.25) arkimet does not scan anymore the radar polar volume data provided by DPC, the error is:

```
2020-05-29 15:57:24+00:00 |3888|importing configured odim:ZOUFPLAN.hdf
Traceback (most recent call last):
  File "/etc/arkimet/scan/odimh5.py", line 248, in <module>
    scan(f, metadata)
  File "/etc/arkimet/scan/odimh5.py", line 177, in scan
    odimh5_pvol_set_area(h5f, md)
  File "/etc/arkimet/scan/odimh5.py", line 98, in odimh5_pvol_set_area
    radhor = group["how"].attrs.get("radhoriz")
  File "/usr/lib64/python2.7/site-packages/h5py/_hl/group.py", line 153, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5o.pyx", line 183, in h5py.h5o.open (h5py/h5o.c:3246)
KeyError: "Unable to open object (Object 'how' doesn't exist)"
ERROR scanner /etc/arkimet/scan/odimh5.py returned error code 1
```

**Comment by dcesari** [comment]
[odim.zip](https://github.com/ARPA-SIMC/arkimet/files/4702897/odim.zip)
An example is attached

**Comment by edigiacomo** [comment]
Just for the record, the Lua scanner was:

```
local radhor = odimh5:find_attr(ds .. "/how", "radhoriz")
```

the return value is nil if the group (i.e. `how`) or the attribute (`radhoriz`) is missing and the resulting `radius` value is 0:

```
Area: ODIMH5(lat=46562500, lon=12970300, radius=0)
```

**Comment by dcesari** [comment]
Now it works without errors:
```
./run-local src/arki-scan --yaml odimh5:ZOUFPLAN.hdf
Source: BLOB(odimh5,/scratch/dcesari/github/arkimet/ZOUFPLAN.hdf:0+516709)
Origin: ODIMH5(16106, , )
Product: ODIMH5(PVOL, SCAN)
Level: ODIMH5(-0.2, 16)
Reftime: 2020-05-29T15:03:00Z
Area: ODIMH5(lat=46562500, lon=12970300, radius=0)
Task: DPC Standard Scan
Quantity: DBZH, QIND, VRAD
Note: [2020-06-03T08:47:53Z]Scanned from ZOUFPLAN.hdf
```
the metadata are the same which were previously obtained with the lua scanner.
