### ISSUE TITLE
arki-query return duplicate record

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#271]
```
[arkimet@arkioss8 ~]$ arki-query --data 'area:VM2,4063;product:VM2,167;reftime:=2020-08-30T00:00'  /arkivio/arkimet/dataset/fidupo
202008300000,4063,167,9791,,,054000000
202008300000,4063,167,979.1,,,000000000
```
```
[arkimet@arkioss8 ~]$ arki-check  --filter='reftime:=2020-08-30' --fix /arkivio/arkimet/dataset/fidupo
fidupo:2020/08-30.vm2: item at offset 125465 is wrongly ordered before item at offset 1934733

[arkimet@arkioss8 ~]$ arki-check  --filter='reftime:=2020-08-30' -fr /arkivio/arkimet/dataset/fidupo
fidupo:2020/08-30.vm2: item at offset 125465 is wrongly ordered before item at offset 1934733
Traceback (most recent call last):
  File "/usr/bin/arki-check", line 11, in <module>
    main()
  File "/usr/bin/arki-check", line 7, in main
    sys.exit(Check.main())
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/base.py", line 75, in main
    cmd.run()
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/check.py", line 125, in run
    arki_check.repack()
RuntimeError: duplicate detected while reordering segment
```

The data were imported using arki-scan

```
[arkimet@arkioss8 ~]$ arki-query --dump 'area:VM2,4063;product:VM2,167;reftime:=2020-08-30T00:00'  /arkivio/arkimet/dataset/fidupo
Source: BLOB(vm2,/arkivio/arkimet/dataset/fidupo/2020/08-30.vm2:53313+38)
Product: VM2(167, bcode=B10004, lt1=1, p1=0, p2=0, tr=254, unit=hPa)
Reftime: 2020-08-30T00:00:00Z
Area: VM2(4063,lat=4456500, lon=833722, rep=fidupo)
Value: 9791,,,054000000
Note: [2020-09-15T07:01:20Z]Scanned from 08-30.vm2

Source: BLOB(vm2,/arkivio/arkimet/dataset/fidupo/2020/08-30.vm2:1926042+39)
Product: VM2(167, bcode=B10004, lt1=1, p1=0, p2=0, tr=254, unit=hPa)
Reftime: 2020-08-30T00:00:00Z
Area: VM2(4063,lat=4456500, lon=833722, rep=fidupo)
Value: 979.1,,,000000000
Note: [2021-08-26T16:03:17Z]Scanned from da-caricare2.vm2
```

**Comment by edigiacomo** [comment]
Chiudo la issue, ormai stale.
