### ISSUE TITLE
test errors during builds

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#290]
This impacts all distributions.

Full logs: https://simc.arpae.it/moncic-ci/arkimet/last/master/

Relevant bit:
```
======================================================================
ERROR: test_cosmo_nudging (tests.test_scan_grib.TestScanGrib)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/rpmbuild/BUILD/arkimet/python/tests/test_scan_grib.py", line 349, in test_cosmo_nudging
    self.assertEqual(mds[0]["timerange"], "Timedef(0s, 254, 0s)")
KeyError: "section not found: 'timerange'"

======================================================================
ERROR: test_ninfa (tests.test_scan_grib.TestScanGrib)
----------------------------------------------------------------------
 Traceback (most recent call last):
   File "/root/rpmbuild/BUILD/arkimet/python/tests/test_scan_grib.py", line 270, in test_ninfa
     self.assertEqual(mds[0]["timerange"], "Timedef(0s, 254, 0s)")
 KeyError: "section not found: 'timerange'"
 
======================================================================
ERROR: test_utm_areas (tests.test_scan_grib.TestScanGrib)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/rpmbuild/BUILD/arkimet/python/tests/test_scan_grib.py", line 285, in test_utm_areas
    self.assertEqual(mds[0]["origin"], "GRIB2(00200, 00000, 000, 000, 203)")
KeyError: "section not found: 'origin'"

----------------------------------------------------------------------
```

**Comment by brancomat** [comment]
this is actually a eccodes-simc issue: https://github.com/ARPA-SIMC/eccodes-simc/issues/8
