### ISSUE TITLE
ImportError: cannot import name 'cmdline'

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#304]
The last version fails on RH-based distro:

 ```
# Rocky 8
$ rpm -qi arkimet | grep -i version
Version     : 1.46
$ arki-query --version
Traceback (most recent call last):
  File "/usr/bin/arki-query", line 2, in <module>
    from arkimet.cmdline.query import Query
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/query.py", line 7, in <module>
    from arkimet.cmdline.base import AppConfigMixin, AppWithProcessor, Exit
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/base.py", line 11, in <module>
    from . import cmdline
ImportError: cannot import name 'cmdline'

# Fedora 36
$ rpm -qi arkimet | grep -i version
Version     : 1.46
$ arki-query --version
Traceback (most recent call last):
  File "/usr/bin/arki-query", line 2, in <module>
    from arkimet.cmdline.query import Query
  File "/usr/lib/python3.10/site-packages/arkimet/cmdline/query.py", line 7, in <module>
    from arkimet.cmdline.base import AppConfigMixin, AppWithProcessor, Exit
  File "/usr/lib/python3.10/site-packages/arkimet/cmdline/base.py", line 11, in <module>
    from . import cmdline

```

I don't understand why on Ubuntu Jammy the same version works fine.

**Comment by spanezz** [comment]
`cmdline.py` and `maint.py` are missing from `/usr/lib/python3.6/site-packages/arkimet/cmdline/`on rocky8, although they are listed on `python/meson.build`. However, they are not listed in `python/Makefile.am`
