### ISSUE TITLE
Missing python dependencies in debian package

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#308]
With `arkimet-1.47-1`:

```
Traceback (most recent call last):
  File "/usr/bin/arki-scan", line 11, in <module>
    main()
  File "/usr/bin/arki-scan", line 7, in main
    sys.exit(Scan.main())
  File "/usr/lib/python3/dist-packages/arkimet/cmdline/base.py", line 85, in main
    return cmd.run()
  File "/usr/lib/python3/dist-packages/arkimet/cmdline/scan.py", line 164, in run
    return arki_scan.dispatch_sections(
  File "/usr/lib/python3.10/logging/__init__.py", line 1488, in warning
    if self.isEnabledFor(WARNING):
  File "/etc/arkimet/scan/nc.py", line 1, in <module>
    from arkimet.scan.nc import Scanner
  File "/usr/lib/python3/dist-packages/arkimet/scan/nc.py", line 3, in <module>
    import netCDF4
ModuleNotFoundError: No module named 'netCDF4'
```

python3-netcdf4 is not among among the dependencies:

```
$ monci run ubuntujammy apt-cache depends python3-arkimet
python3-arkimet
  Depends: python3-wreport
  Depends: python3-dballe
  Depends: libc6
  Depends: libgcc-s1
  Depends: libstdc++6
  Depends: python3
  Depends: python3
  Depends: <python3:any>
    python3
```

If I understand correctly, `${python3:Depends}` works with native Python packages but in this case it misses the dependencies.

**Comment by edigiacomo** [comment]
I'm releasing a new version 1.47-2 with explicit python3 dependencies (see 632adec). I do not close the issue because I don't know if there's a more idiomatic way to do it.

**Comment by spanezz** [comment]
I think you did well, and I cannot think of a better way in this case
