### ISSUE TITLE
query fails for permission denied

### ISSUE THREAD

**Issue by lidiabressan** [ARPA-SIMC/arkimet#314]
ciao,

If I make a query with an other user, the query fails because of permission problems:

```
[ma_aria@maialinux]$ arki-query --data --sort=reftime,timerange,-level "  product: GRIB1,,2,8; level: hld4546 or hld4445 or hld4344 or hld4243 or hld4142 or hld4041 or hld3940 or hld3839 or hld3738 or hld3637 or hld3536 or hld3435 or hld3334 or hld3233 or hld3132 or hld3031 or hld2930 or hld2829 or hld2728 or hld2627 or hld2526 or hld2425 or hld2324 or hld2223 or hld2122 or hld2021 or hld1920 or hld1819 or hld1718 or hld1617 or hld1516;  ;" /fs/archive/ma_cams/METEO_ARC/cosmo_arki/dataset/cosmo_5M*  /fs/archive/ma_cams/METEO_ARC/cosmo_arki/dataset/cosmo_alti > prova.grb

WARNING cosmo_alti failed: cannot open file /fs/archive/ma_cams/METEO_ARC/cosmo_arki/dataset/cosmo_alti/2017/09-05.grib.lock: Permission denied
WARNING cosmo_5M_medl_sm failed: cannot open file /fs/archive/ma_cams/METEO_ARC/cosmo_arki/dataset/cosmo_5M_medl_sm/2018/07-31.grib.lock: Permission denied
WARNING cosmo_5M_medl failed: cannot open file /fs/archive/ma_cams/METEO_ARC/cosmo_arki/dataset/cosmo_5M_medl/2018/07-31.grib.lock: Permission denied
Traceback (most recent call last):
  File "/usr/bin/arki-query", line 11, in <module>
    main()
  File "/usr/bin/arki-query", line 7, in main
    sys.exit(Query.main())
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/base.py", line 83, in main
    return cmd.run()
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/query.py", line 177, in run
    raise Exit(arki_query.query_sections())
RuntimeError: cannot create directory /fs/archive/ma_cams/METEO_ARC/cosmo_arki/dataset/cosmo_5M_itr/.summaries: Permission denied
```

Should I change permissions ? Any suggestion ?

Thanks !

**Comment by dcesari** [comment]
It is a known problem, see also #258, no simple solution, it is probably better to maintain an arki-server (i'll explain it separately).
