### ISSUE TITLE
check on different datasets

### ISSUE THREAD

**Issue by lidiabressan** [ARPA-SIMC/arkimet#343]
ciao,

I would like to check (and delete) a forecast datum if there is the corresponding analysis.
Analysis and forecast are in different datasets, with different origin (in filter).
The index of the datasets are:

index = reftime, timerange, product, level

My idea would be:

- select a reftime
- query the analysis dataset (based on reftimes) and collect index keys (reftime_an, product, level, timerange_an)
- query forecast metadata based on a reftime (reftime, product, level, timerange) and 
   convert the index of the forecast into the analysis ones (reftime_an, product, level, timerange_an)
- check if (reftime_an, product, level, timerange_an) is in the analysis collection
- if yes: write the forecast metadata for deletion in a file
- delete selected forecast with arki-check --fix --remove file_with_metadata_to_delete.md  ${dataset_fc} (orwith python, I don't know how)

Questions:

How do I delete data?
To delete messages, do I need the whole metadata or the index keys are enough (as in queries)?

Which format should I use to write the metadata of data to delete ?

I don't know how to append the metadata to the file: md.write(file, format='json') has just one message.

   
   
   
   
   
my tentative idea:

  
  

```

class Checker:
    def fc_with_an(self, md):
        reftime = md.to_python("reftime")["time"]
        try:
            product = md.to_string("product")
            origin = md.to_string("origin")
            level = md.to_string("level")
            timerange = md.to_python("timerange")
        except KeyError:
            product = None

        if origin in [origin_icon['all5km_fc']]:
            if timerange['step_unit'] == 1 and timerange['step_len']>=1:
                reftime_an = reftime + dt.timedelta(hours=timerange['step_len']-1)
            elif timerange['step_unit'] == 1 and timerange['step_len']==0:
                non_succede
            elif timerange['step_unit'] == 13 and timerange['step_len']==0:
                reftime_an = reftime + dt.timedelta(hours=-1)
            elif timerange['step_unit'] == 13 and timerange['step_len']>0:
                non_succede
            else:
                non_succede
            ## timerange
            if timerange['stat_type'] == 254:
                assert timerange['stat_len'] == 0
                timerange_an = 'Timedef(1h, 254, 0s)'
            elif timerange['stat_type']==1:
                ## cum - product == total_precipitation:
                assert timerange['step_len'] == timerange['stat_len']
                timerange_an = 'Timedef(1h, 1, 1h)'
            elif timerange['stat_type']==0:
                ## average - heat, radiation
                assert timerange['step_len'] == timerange['stat_len']
                timerange_an = 'Timedef(1h, 0, 1h)'
            else:
                non_succede
            chiave_fc = (reftime, product, level, md.to_string("timerange"))
            chiave_an = (reftime_an, product, level, timerange_an)
            self.db_fc_elements.append( (chiave_fc, chiave_an) )
            if chiave_an in self.db_an_elements:
                file_md_to_delete = "file_md_to_delete.md"
                print(file_md_to_delete)
                md.write(file_md_to_delete, format="json", skip_data=True)
        else:
            chiave_an = (reftime, product, level, md.to_string("timerange"))
            self.db_an_elements.append( chiave_an )

            
            

q_reftime_fc = "reftime: = {};".format(args.reftime)
q_reftime_an = "reftime: >= {}, <= {};".format(args.reftime -dt.timedelta(hours=1), \
                                                                                args.reftime +dt.timedelta(hours=73))

with arki.dataset.Session() as session:
    cfg_fc = arki.dataset.read_config(path_dataset + args.dataset+'_fc')
    cfg = arki.dataset.read_config(path_dataset + args.dataset)
    
    with session.dataset_reader(cfg=cfg) as ds:
        ds.query_data(q_reftime_an, on_metadata=checker.fc_to_an_md )
        
    with session.dataset_reader(cfg=cfg_fc) as ds_fc:
        ds_fc.query_data(q_reftime_fc, on_metadata=checker.fc_to_an_md )
```

Any suggestion is very welcome!

Thanks

Lidia

**Comment by lidiabressan** [comment]
I still have a problem (a bug?). 
It seems it works (the python check). But I have an error in the command `arki-check --fix --remove .. ` :  it looks for the file where I run the arki-check command instead of in the archive path:

`
$ arki-check --fix --remove to_delete.md  $path_icon_arki/dataset/icon_2I_all5km_fc

Traceback (most recent call last):
  File "/usr/bin/arki-check", line 11, in <module>
    main()
  File "/usr/bin/arki-check", line 7, in main
    sys.exit(Check.main())
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/base.py", line 85, in main
    return cmd.run()
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/check.py", line 129, in run
    self.arki_check.remove(self.args.remove)
RuntimeError: cannot stat ICON/2024/12-27.grib: No such file or directory

$ pwd
ICON

$ ll $path_icon_arki/dataset/icon_2I_all5km_fc/2024/12-27.grib
-rw-rw-r-- 1 user user 8292852720 Dec 27 08:42 $path_icon_arki/dataset/icon_2I_all5km_fc/2024/12-27.grib
`

**Comment by brancomat** [comment]
This is strange, as @spanezz said:
> if you run `arki-dump to-delete.md` you should see the `Source:` entries pointing to files in the dataset

but I knew that you can inspect the content of `to_delete.md` also with
```
arki-scan --yaml arkimet:to_delete.md
```

The two tools gave me different results with the same file:
```
$ arki-dump /tmp/test.md|grep Source
Source: BLOB(grib,/tmp/arkivio/arkimet/dataset/ifs_ita010/2025/01-21.grib:0+43820)
(...)

$ arki-scan --yaml arkimet:/tmp/test.md|grep Source
Source: BLOB(grib,/arkivio/arkimet/dataset/ifs_ita010/2025/01-21.grib:0+43820)
```

So I have no answers but other questions for @spanezz :
1) why do the two tools give different output?
2) since in `arki-check --remove $metadata_file` the dataset parameter isn't optional, what happens when the Source field in the metadata and the dataset differ?

**Comment by lidiabressan** [comment]
I always get the same path, and always the to_delete.md path.

$ arki-scan --yaml arkimet:to_delete.md|grep Source
Source: BLOB(grib,/lhome/ma_cams/svn/lavoro_procedure/catena_operativa_aria/Meteo/2024/12-27.grib:0+271076)

$ cp to_delete.md ICON/
$  arki-scan --yaml arkimet:ICON/to_delete.md|grep Source
Source: BLOB(grib,/lhome/ma_cams/svn/lavoro_procedure/catena_operativa_aria/Meteo/ICON/2024/12-27.grib:0+271076)

**Comment by spanezz** [comment]
To answer why the tools give different output, the metadata file does not need to contain full pathnames and can contain pathnames relative to the metadata file itself. That can cause ambiguities, and wasn't particularly well handled until the refactoring I've done recently for #344. From the output @brancomat sent, it looks potentially like a bug, which I'd try to reproduce again in the `segment` branch of #344

**Comment by spanezz** [comment]
With regards to @lidiabressan not being able to remove files, it's because the files are in the archives, and I had assumed the files were in the online part of the dataset. Arkimet was unable to delete files from the archives. From #344 it is able to, but it refuses to do it (see @brancomat's request at https://github.com/ARPA-SIMC/arkimet/issues/344#issuecomment-2577473931)

In the `segments` branch it is however possible to query `.archive/last` and other archive directories as if they were normal datasets, and use `arki-check --delete` on them. That is my proposed way to delete from the archives while still avoiding accidentally deleting files from archives in normal dataset operations.

**Comment by lidiabressan** [comment]
I just checked, my dataset are online and not in archives (I attach the config file).

The error I get is about deleting data in online archives.
If the problem is the missing path, is there a way to force to write the absolute path in the metadata?

Thanks


config file:

[duplicates]
name = duplicates
path = /fs/archive/ma_cams/METEO_ARC/icon_arki/dataset/duplicates
step = daily
type = duplicates

[error]
name = error
path = /fs/archive/ma_cams/METEO_ARC/icon_arki/dataset/error
step = daily
type = error

[icon_2I_all5km]
description = ICON 5km volumes, original domain
filter = origin: GRIB2,80,255,4,0,61; area: GRIB:Ni=326,Nj=391;
format = grib
index = reftime, timerange, product, level
name = icon_2I_all5km
path = /fs/archive/ma_cams/METEO_ARC/icon_arki/dataset/icon_2I_all5km
postprocess = singlepoint, subarea, seriet
replace = yes
step = daily
type = iseg
unique = reftime, timerange, product, level

[icon_2I_all5km_fc]
description = ICON 5km volumes, original domain, forecast
filter = origin: GRIB2,80,255,2,0,62; area: GRIB:Ni=326,Nj=391;
format = grib
index = reftime, timerange, product, level
name = icon_2I_all5km_fc
path = /fs/archive/ma_cams/METEO_ARC/icon_arki/dataset/icon_2I_all5km_fc
postprocess = singlepoint, subarea, seriet
replace = yes
step = daily
type = iseg
unique = reftime, timerange, product, level

[icon_2I_ita2km]
description = ICON 2km volumes, ita2km, restricted Italian domain
filter = origin: GRIB2,80,255,4,0,61; area: GRIB:Ni=485,Nj=596;
format = grib
index = reftime, timerange, product, level
name = icon_2I_ita2km
path = /fs/archive/ma_cams/METEO_ARC/icon_arki/dataset/icon_2I_ita2km
postprocess = singlepoint, subarea, seriet
replace = yes
step = daily
type = iseg
unique = reftime, timerange, product, level

[icon_2I_ita2km_fc]
description = ICON 2km volumes, ita2km, restricted Italian domain, forecast
filter = origin: GRIB2,80,255,2,0,62; area: GRIB:Ni=485,Nj=596;
format = grib
index = reftime, timerange, product, level
name = icon_2I_ita2km_fc
path = /fs/archive/ma_cams/METEO_ARC/icon_arki/dataset/icon_2I_ita2km_fc
postprocess = singlepoint, subarea, seriet
replace = yes
step = daily
type = iseg
unique = reftime, timerange, product, level

**Comment by lidiabressan** [comment]
solved!

            md_fc.make_absolute()  # added line
            md_fc.write(out)

thanks
