### ISSUE TITLE
Empty reply from arki-server using expa

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#53]
Arkimet version: `v1.0-14`

```
$ arki-query --summary --dump --summary-restrict=reftime 'reftime:=today 00:00; product:GRIB1,200,2,2; level:GRIB1,102; timerange:GRIB1,0,0h,0h' http://maialinux.metarpa:8090/dataset/COSMO_I7 | grep Size
  Size: 186250
$ arki-query --data 'reftime:=today 00:00; product:GRIB1,200,2,2; level:GRIB1,102; timerange:GRIB1,0,0h,0h' http://maialinux.metarpa:8090/dataset/COSMO_I7 | wc -c
186250
$ echo "ds:COSMO_I7. d:@. t:0000. s:GRIB1/0/0h/0h. l:GRIB1/102. v:GRIB1/200/2/2." > expa
$ arki-query --data --qmacro="expa 2016-09-21" --file=expa http://maialinux.metarpa:8090
while Performing query at http://maialinux.metarpa:8090/query: Server returned nothing (no headers, no data)(Empty reply from server)
$ arki-query --data --qmacro="expa 2016-09-21" --file=expa http://maialinux.metarpa:8090/dataset/COSMO_I7
while Performing query at http://maialinux.metarpa:8090/query: Server returned nothing (no headers, no data)(Empty reply from server)
$ arki-query --summary --dump --qmacro="expa 2016-09-21" --file=expa http://maialinux.metarpa:8090/dataset/COSMO_I7
while Performing query at http://maialinux.metarpa:8090/summary: Server returned nothing (no headers, no data)(Empty reply from server)
```
`server-error.log` is empty.
`server-access.log`:
```
172.20.5.151 - - [21/Sep/2016:14:31:32 +0000] "GET /dataset/COSMO_I7/config HTTP/1.1" 200 -
```

Running the query locally:
```
[lm_ope@maialinux ~]$ arki-query --data --qmacro='expa 2016-09-21' --file=expa /ope/lm_ope/arkimet/COSMO_I7 | wc -c
186250
```

**Comment by brancomat** [comment]
andando direttamente su url: http://maialinux.metarpa:8090/query

si ottiene un messaggio `file .lua not found; tried: /etc/arkimet/qmacro`

il contenuto di /etc/arkimet/qmacro non è cambiato (rispetto ad esempio ad arkimet-1.0-7 che non dà questo problema)

questo il log di errore corrispondente:
```
2016-09-22 15:52:53,215 ERROR Exception caught after headers have been sent
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/arkimet/server/views.py", line 271, in run
    self.stream()
  File "/usr/lib/python3.3/site-packages/arkimet/server/views.py", line 350, in stream
    self.get_dataset_reader().query_data(
  File "/usr/lib/python3.3/site-packages/arkimet/server/views.py", line 448, in get_dataset_reader
    self.request.form.get("query", "").strip()
RuntimeError: file .lua not found; tried: /etc/arkimet/qmacro
```

**Comment by spanezz** [comment]
Riprodotto il problema in test suite:
```
$ eatmydata make check -C python
…
Segmentation fault
```
