### ISSUE TITLE
NameError: name 'NotFound' is not defined

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#61]
When querying a nonexistent dataset

```
2016-11-09 13:13:11,270 ERROR Exception caught after headers have been sent
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/arkimet/server/views.py", line 119, in run
    self.stream()
  File "/usr/lib/python3.4/site-packages/arkimet/server/views.py", line 248, in stream
    raise NotFound("Dataset {} not found".format(self.kwargs["name"]))
NameError: name 'NotFound' is not defined
```

**Comment by spanezz** [comment]
<3 NotFound not found
