### ISSUE TITLE
qmacro expa shouldn't log any error when query is not satisfied

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#69]
This type of error in arki-server log can be removed:
```
2017-01-02 14:09:58,471 ERROR Exception caught after headers have been sent
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/arkimet/server/views.py", line 273, in run
    self.stream()
  File "/usr/lib/python3.3/site-packages/arkimet/server/views.py", line 310, in stream
    data_start_hook=self.send_headers)
RuntimeError: cannot run queryData function: /etc/arkimet/qmacro/expa.lua:184: Query cannot be satisfied
```

**Comment by spanezz** [comment]
The error comes from `expa.lua`, and if "cannot be satisfied" is somehow a normal behaviour, I can turn the error into something else. Would it be better to make it so that, say, if the query cannot be satisfied then no output is produced, but the query is successful?

**Comment by edigiacomo** [comment]
When an expa query cannot be satisfied, arki-query exit with status 1 and arki-server output an error in the log file. We check the exit status in our programs, but the error message is so frequent that it can be considered noise.

@brancomat what do you think? I like Enrico's suggestion, because we can distinguish an error (exit status != 0) from a failed query (output file is empty), but we should modify our programs (maybe `simcop` only).
