### ISSUE TITLE
arki-check -r: too many open files

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#82]
With dataset `type = iseg`:

```
$ arki-check -fr --debug boa
...
boa:2014/09-16.vm2: repacked (0 freed)
boa:2014/09-17.vm2: repacked (0 freed)
boa:2014/09-18.vm2: repacked (0 freed)
boa:2014/09-19.vm2: repacked (0 freed
cannot open file /arkivio/arkimet/dataset/boa/2014/09-20.vm2.repack:  Too many open files
```

**Comment by edigiacomo** [comment]
Maybe I've found the problem: [the unique_ptr release the resource (a `Segment`) instead of destroying it](https://github.com/ARPA-SIMC/arkimet/blob/v1.1-1/arki/dataset/segment/fd.cc#L449). The file is not closed because the object is never destroyed.

`gdb` backtrace (break on `open`):

```
#0  open64 () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff79c2025 in open (__oflag=577, __path=<optimized out>) at /usr/include/bits/fcntl2.h:59
#2  arki::utils::sys::File::open (this=this@entry=0x55555578b550, flags=flags@entry=577, mode=mode@entry=438) at utils/sys.cc:700
#3  0x00007ffff7aaef53 in arki::dataset::segment::fd::Segment::truncate_and_open (this=this@entry=0x55555578b500) at dataset/segment/fd.cc:154
#4  0x00007ffff7ab188d in arki::dataset::segment::lines::make_repack_segment (relname="2016/01-01.vm2.repack", 
    absname="/home/edg/tmp/boa/2016/01-01.vm2.repack") at dataset/segment/lines.cc:69
#5  0x00007ffff7aafaa8 in arki::dataset::segment::fd::Segment::repack (rootdir="/home/edg/tmp/boa", relname="2016/01-01.vm2", mds=..., 
    make_repack_segment=make_repack_segment@entry=0x7ffff7ab1860 <arki::dataset::segment::lines::make_repack_segment(std::__cxx11::string const&, std::__cxx11::string const&)>, skip_validation=skip_validation@entry=false, test_flags=0) at dataset/segment/fd.cc:426
#6  0x00007ffff7ab1525 in arki::dataset::segment::lines::Segment::repack (this=0x55555578b380, rootdir="/home/edg/tmp/boa", mds=..., test_flags=0)
    at dataset/segment/lines.cc:76
#7  0x00007ffff7aac862 in arki::dataset::segment::(anonymous namespace)::BaseSegmentManager::repack (this=0x555555a9e060, relname="2016/01-01.vm2", 
    mds=..., test_flags=0) at dataset/segment.cc:130
#8  0x00007ffff7b055dd in arki::dataset::iseg::Checker::repackSegment (this=<optimized out>, relpath="2016/01-01.vm2", test_flags=0)
    at dataset/iseg/writer.cc:648
#9  0x00007ffff7ab81dc in arki::dataset::maintenance::RealRepacker::operator() (this=0x55555578ffb0, relpath="2016/01-01.vm2", state=...)
    at dataset/maintenance.cc:165
#10 0x00007ffff7ae7058 in arki::dataset::segmented::Checker::repack (this=this@entry=0x555555787000, reporter=..., writable=writable@entry=true, 
    test_flags=test_flags@entry=0) at dataset/segmented.cc:296
#11 0x00007ffff7b02c4c in arki::dataset::iseg::Checker::repack (this=0x555555787000, reporter=..., writable=<optimized out>, test_flags=0)
    at dataset/iseg/writer.cc:502
#12 0x000055555555b1b5 in Repacker::operator() (this=0x555555788fc0, w=...) at arki-check.cc:165
#13 0x0000555555559d76 in WorkerOnWritable::process (cfg=..., this=0x555555788fc0) at arki-check.cc:133
#14 main (argc=<optimized out>, argv=<optimized out>) at arki-check.cc:388
```

Another evidence is given by `valgrind`:

```
==15940== 230 (128 direct, 102 indirect) bytes in 1 blocks are definitely lost in loss record 147 of 187
==15940==    at 0x4C2C20C: operator new(unsigned long) (vg_replace_malloc.c:334)
==15940==    by 0x4FFD873: arki::dataset::segment::lines::make_repack_segment(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator$
char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (lines.cc:68)
==15940==    by 0x4FFBAA7: arki::dataset::segment::fd::Segment::repack(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> $
 const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, arki::metadata::Collection&, arki::dataset::segment:$
fd::Segment* (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_t$
aits<char>, std::allocator<char> > const&), bool, unsigned int) (fd.cc:426)
==15940==    by 0x4FFD524: arki::dataset::segment::lines::Segment::repack(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<cha$
> > const&, arki::metadata::Collection&, unsigned int) (lines.cc:76)
==15940==    by 0x4FF8861: arki::dataset::segment::(anonymous namespace)::BaseSegmentManager::repack(std::__cxx11::basic_string<char, std::char_trait$
<char>, std::allocator<char> > const&, arki::metadata::Collection&, unsigned int) (segment.cc:130)
==15940==    by 0x50515DC: arki::dataset::iseg::Checker::repackSegment(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> $
 const&, unsigned int) (writer.cc:648)
==15940==    by 0x50041DB: arki::dataset::maintenance::RealRepacker::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocat$
r<char> > const&, arki::dataset::segment::State) (maintenance.cc:165)
==15940==    by 0x5033057: arki::dataset::segmented::Checker::repack(arki::dataset::Reporter&, bool, unsigned int) (segmented.cc:296)
==15940==    by 0x504EC4B: arki::dataset::iseg::Checker::repack(arki::dataset::Reporter&, bool, unsigned int) (writer.cc:502)
==15940==    by 0x10F1B4: Repacker::operator()(arki::dataset::Checker&) (arki-check.cc:165)
==15940==    by 0x10DD75: process (arki-check.cc:133)
==15940==    by 0x10DD75: main (arki-check.cc:388)
```
