### ISSUE TITLE
Exception caught after headers have been sent in logfile

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/arkimet#97]
In server-error.log I found a lot of those messages:
```
2017-06-21 18:23:50,581 ERROR Exception caught after headers have been sent
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/arkimet/server/views.py", line 275, in run
    self.stream()
  File "/usr/lib/python3.3/site-packages/arkimet/server/views.py", line 301, in stream
    summary.write(self.handler.wfile, format=self.request.values.get("style", "binary").strip())
SystemError: error return without exception set
```
TODO
how to reproduce

**Comment by spanezz** [comment]
Duplicato di #71

**Comment by brancomat** [comment]
Chiudo in quanto duplicato
